### ISSUE TITLE
Reach out to the Active Learning Labs to ask for Raspberry Pis

### ISSUE THREAD

**Issue by leohentschker** [leohentschker/village-reach#2]

**Comment by Ivraj** [comment]
I talked to Yasha, one of the Active Learning Lab peepz. He told me all their suppliers are out of Raspberry Pis, and they're giving all their available ones to ES100 students, so we wouldn't be able to use them. Now, whether or not they're ENTIRELY out is a diff question. I'll keep my eye out for anything. 

Otherwise, the average price for one from Amazon is like ~$40 I think.

**Comment by leohentschker** [comment]
That's reasonable but annoying and thanks for asking them!

That means we'll need to ask @urbkn7 if it's possible to get one through D4D or worst comes to worst I can just buy one.
